server:
  port: 0
spring:  application:    name: user-service
  h2:    console:      enabled: true
      settings:        web-allow-others: true
      path: /console
eureka:  client:    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true      